const estados = ["aguascalientes",
    "baja california",
    "baja california sur",
    "campeche",
    "cdmx",
    "chiapas",
    "chihuahua",
    "coahuila",
    "colima",
    "durango",
    "estado de mexico",
    "guanajuato",
    "guerrero",
    "hidalgo",
    "jalisco",
    "michoacan de ocampo",
    "morelos",
    "nayarit",
    "nuevo leon",
    "oaxaca",
    "puebla",
    "queretaro de arteaga",
    "quintana roo",
    "san luis potosi",
    "sinaloa",
    "sonora",
    "tabasco",
    "tamaulipas",
    "tlaxcala",
    "veracruz de ignacio de la llave",
    "yucatan",
    "zacatecas"]

const info_estados = {
    "aguascalientes": { superficie: '5,616 km²', capital: 'Aguascalientes', poblacion: '1,425,607' },
    "baja california": { superficie: '71,450 km²', capital: 'Mexicali', poblacion: '3,769,020' },
    "baja california sur": { superficie: '75,675 km²', capital: 'La Paz', poblacion: '798,447' },
    "campeche": { superficie: '57,484.9 km²', capital: 'Campeche', poblacion: '928,363' },
    "ciudad de mexico": { superficie: '1,495 km²​', capital: 'Iztapalapa', poblacion: '9,209,944 hab' },
    "chiapas": { superficie: '73,311 km²', capital: 'Tuxtla Gutiérrez', poblacion: '5,543,828' },
    "chihuahua": { superficie: '247,455 km²', capital: 'Chihuahua', poblacion: '3,741,869' },
    "coahuila": { superficie: '151,571 km²', capital: 'Saltillo', poblacion: '13,146,771' },
    "colima": { superficie: '5,625 km²', capital: 'Colima', poblacion: '1,425,607' },
    "durango": { superficie: '123,364 km²', capital: 'Durango', poblacion: '1,832,650' },
    "estado de mexico": { superficie: '22,499.95 km²', capital: 'Toluca', poblacion: '16,992,418' },
    "guanajuato": { superficie: '30,608 km²', capital: 'Guanajuato', poblacion: '6,166,934' },
    "guerrero": { superficie: '64,281 km²', capital: 'Chilpancingo de los Bravo', poblacion: '3,540,684' },
    "hidalgo": { superficie: '20,821 km²', capital: 'Pachuca de Soto', poblacion: '3,082,841' },
    "jalisco": { superficie: '78,588 km²', capital: 'Guadalajara', poblacion: '8,348,151' },
    "michoacan de ocampo": { superficie: '58,599 km²', capital: 'Morelia', poblacion: '4,748,846' },
    "morelos": { superficie: '4,950 km²', capital: 'Cuernavaca', poblacion: '1,971,520' },
    "nayarit": { superficie: '27,857 km²', capital: 'Tepic', poblacion: '1,235,456' },
    "nuevo leon": { superficie: '64,924 km²', capital: 'Monterrey', poblacion: '5,784,442' },
    "oaxaca": { superficie: '93,952 km²', capital: 'Oaxaca de Juárez', poblacion: '4,132,148' },
    "puebla": { superficie: '34,251 km²', capital: 'Puebla', poblacion: '6,583,278' },
    "queretaro de arteaga": { superficie: '11,699 km²', capital: 'Querétaro', poblacion: '2,368,467' },
    "quintana roo": { superficie: '50,212 km²', capital: "Bacalar", poblacion: '1,857,985' },
    "san luis potosi": { superficie: '65,268 km²', capital: 'San Luis Potosí', poblacion: '2,822,255' },
    "sinaloa": { superficie: '58,200 km²', capital: 'Culiacán', poblacion: '3,026,943' },
    "sonora": { superficie: '179,355 km²', capital: 'Hermosillo', poblacion: '2,944,840' },
    "tabasco": { superficie: '25,267 km²', capital: 'Centro', poblacion: '2,402,598' },
    "tamaulipas": { superficie: '80,249 km²', capital: 'Reynosa', poblacion: '3,527,735' },
    "tlaxcala": { superficie: '3,997 km²', capital: 'Tlaxcala', poblacion: '1,342,977' },
    "veracruz de ignacio de la llave": { superficie: '78,82 km²', capital: 'Xalapa', poblacion: '405,952' },
    "yucatan": { superficie: '43,379 km²', capital: 'Mérida', poblacion: '2,320,898' },
    "zacatecas": { superficie: '75 275.3 km²', capital: 'Zacatecas', poblacion: '1,622,138' }
}

// const info_estados = {
//     "aguascalientes": { superficie: 100, capital: 'Aguascalientes' },
//     "baja california": { superficie: 100, capital: 'Mexicali' },
//     "baja california sur": { superficie: 100, capital: 'La Paz' },
//     "campeche": { superficie: 100, capital: 'Campeche' },
//     "ciudad de mexico": { superficie: 100, capital: 'Iztapalapa' },
//     "chiapas": { superficie: 100, capital: 'Tuxtla Gutiérrez' },
//     "chihuahua": { superficie: 100, capital: 'Chihuahua' },
//     "coahuila": { superficie: 100, capital: 'Saltillo' },
//     "colima": { superficie: 100, capital: 'Colima' },
//     "durango": { superficie: 100, capital: 'Durango' },
//     "estado de mexico": { superficie: 100, capital: 'Toluca' },
//     "guanajuato": { superficie: 100, capital: 'Guanajuato' },
//     "guerrero": { superficie: 100, capital: 'Chilpancingo de los Bravo' },
//     "hidalgo": { superficie: 100, capital: 'Pachuca de Soto' },
//     "jalisco": { superficie: 100, capital: 'Guadalajara' },
//     "michoacan de ocampo": { superficie: 100, capital: 'Morelia' },
//     "morelos": { superficie: 100, capital: 'Cuernavaca' },
//     "nayarit": { superficie: 100, capital: 'Tepic' },
//     "nuevo leon": { superficie: 100, capital: 'Monterrey' },
//     "oaxaca": { superficie: 100, capital: 'Oaxaca de Juárez' },
//     "puebla": { superficie: 100, capital: 'Puebla' },
//     "queretaro de arteaga": { superficie: 100, capital: 'Querétaro' },
//     "quintana roo": { superficie: 100, capital: "Bacalar" },
//     "san luis potosi": { superficie: 100, capital: 'San Luis Potosí' },
//     "sinaloa": { superficie: 100, capital: 'Culiacán' },
//     "sonora": { superficie: 100, capital: 'Hermosillo' },
//     "tabasco": { superficie: 100, capital: 'Centro' },
//     "tamaulipas": { superficie: 100, capital: 'Reynosa' },
//     "tlaxcala": { superficie: 100, capital: 'Tlaxcala' },
//     "veracruz de ignacio de la llave": { superficie: 100, capital: 'Xalapa' },
//     "yucatan": { superficie: 100, capital: 'Mérida' },
//     "zacatecas": { superficie: 100, capital: 'Zacatecas' }
// }